### ISSUE TITLE
functions should be limited in scope

### ISSUE THREAD

**Issue by sosodev** [MostwantedRBX/urlshortener#1]
https://github.com/MostwantedRBX/urlshortener/blob/0b1775aa1d4f09dce7c3633b773ca3bd05000175/src/storage/storage.go#L30

This function not only creates the connection to the database but also builds up the state of the database. Ideally most functions should be limited to doing what their name/docstring implies.

Also, you're duplicating this statement with your retry and the code would be much cleaner if these two weren't intertwined.

**Comment by MostwantedRBX** [comment]
The initialization is in another function now,
