### ISSUE TITLE
Exported types should have doc comments

### ISSUE THREAD

**Issue by sosodev** [MostwantedRBX/urlshortener#2]
https://github.com/MostwantedRBX/urlshortener/blob/0b1775aa1d4f09dce7c3633b773ca3bd05000175/src/storage/storage.go#L56

It's typically considered a requirement for every exported type to have a doc comment. https://github.com/golangci/golangci-lint is often used to enforce these rules.

**Comment by sosodev** [comment]
Also, the name of this function isn't really indicative of what it does. What are we inserting into the DB?

**Comment by MostwantedRBX** [comment]
Wrote doc comments for all exported functions and renamed functions to more relevant names for what they are doing.
