### ISSUE TITLE
Scanning through the whole table does not scale

### ISSUE THREAD

**Issue by sosodev** [MostwantedRBX/urlshortener#3]
https://github.com/MostwantedRBX/urlshortener/blob/0b1775aa1d4f09dce7c3633b773ca3bd05000175/src/storage/storage.go#L77

This SQL statement should select the requestedKey directly like `select key, url from links where requestedKey=$1` and pass in the requested key. This is massively more efficient since you don't have to load the whole table into memory and scan it.

**Comment by MostwantedRBX** [comment]
Used suggestion to use SELECT key, url FROM links WHERE key=$1
