### ISSUE TITLE
Handlers should indicate the type of failure in the response

### ISSUE THREAD

**Issue by sosodev** [MostwantedRBX/urlshortener#4]
https://github.com/MostwantedRBX/urlshortener/blob/4521e1808b46ec86392c8cba6cb646395d033351/src/main.go#L45

This will return status code 200 with no content which typically indicates a successful request. When in actuality this is a bad request and should be specified with `w.WriteHeader(http.BadRequest)` before the return. Even more ideally you could return an error message that indicates why it's a bad request.

**Comment by MostwantedRBX** [comment]
Now returning correct http response if a bad request is made.
