### ISSUE TITLE
Should redirect to the found URL

### ISSUE THREAD

**Issue by sosodev** [MostwantedRBX/urlshortener#5]
https://github.com/MostwantedRBX/urlshortener/blob/4521e1808b46ec86392c8cba6cb646395d033351/src/main.go#L58

I think that's functionally what you're doing with this HTML but you can do it directly with [http.Redirect](https://pkg.go.dev/net/http#Redirect)

**Comment by MostwantedRBX** [comment]
Now uses http.Redirect instead of writing html to the page.
