### ISSUE TITLE
genKey could incorrectly generated a dupliate key

### ISSUE THREAD

**Issue by sosodev** [MostwantedRBX/urlshortener#6]
https://github.com/MostwantedRBX/urlshortener/blob/4521e1808b46ec86392c8cba6cb646395d033351/src/main.go#L116

This doesn't error check and the default value is the empty string so if there was a problem with the fetch the key could falsely be assumed to be valid

**Comment by MostwantedRBX** [comment]
The function now returns nil in the string if the key isn't found and doesn't encounter an error.
