### ISSUE TITLE
Math.rand is not appropriate for generating keys

### ISSUE THREAD

**Issue by sosodev** [MostwantedRBX/urlshortener#7]
https://github.com/MostwantedRBX/urlshortener/blob/4521e1808b46ec86392c8cba6cb646395d033351/src/main.go#L8

`Math.rand` is not truly random and will likely generate insecure, and often duplicate, keys. The crypto package's [rand](https://pkg.go.dev/crypto/rand) is much more preferable.

**Comment by MostwantedRBX** [comment]
It is now using crypto/rand
